STOCKS = [
    "AAPL",
    "ABBV",
    "ACN",
    "ADBE",
    "ADP",
    "AMD",
    "AMGN",
    "AMT",
    "AMZN",
    "APD",
    "AVGO",
    "AXP",
    "BA",
    "BK",
    "BKNG",
    "BMY",
    "BSX",
    "C",
    "CAT",
    "CI",
    "CL",
    "CMCSA",
    "COST",
    "CRM",
    "CSCO",
    "CVX",
    "DE",
    "DHR",
    "DIS",
    "DUK",
    "ELV",
    "EOG",
    "EQR",
    "FDX",
    "GD",
    "GE",
    "GILD",
    "GOOG",
    "GOOGL",
    "HD",
    "HON",
    "HUM",
    "IBM",
    "ICE",
    "INTC",
    "ISRG",
    "JNJ",
    "JPM",
    "KO",
    "LIN",
    "LLY",
    "LMT",
    "LOW",
    "MA",
    "MCD",
    "MDLZ",
    "META",
    "MO",
    "MRK",
    "MSFT",
    "NEE",
    "NFLX",
    "NKE",
    "NOW",
    "NVDA",
    "ORCL",
    "PEP",
    "PFE",
    "PG",
    "PLD",
    "PM",
    "PSA",
    "REGN",
    "RTX",
    "SBUX",
    "SCHW",
    "SLB",
    "SO",
    "SPGI",
    "T",
    "TJX",
    "TMO",
    "TSLA",
    "TXN",
    "UNH",
    "UNP",
    "UPS",
    "V",
    "VZ",
    "WFC",
    "WM",
    "WMT",
    "XOM",
    "BIRK",
    "SRFM"
]
#MAG7 als Default für Tests
DEFAULT_STOCKS = ["AAPL", "MSFT", "GOOGL", "NVDA", "AMZN", "TSLA", "META"]

#ETF Sektoren Performance
SEKTOREN_ETFS = {
    "Technologie": "XLK",
    "Gesundheitswesen": "XLV",
    "Finanzwesen": "XLF",
    "Nicht-Basiskonsumgüter": "XLY",
    "Kommunikationsdienste": "XLC",
    "Industrie": "XLI",
    "Basiskonsumgüter": "XLP",
    "Energie": "XLE",
    "Versorger": "XLU",
    "Immobilien": "XLRE",
    "Rohstoffe": "XLB"
}

TOP_10_SEKTOREN = {
    "Technologie": ["AAPL", "MSFT", "NVDA", "AVGO", "ORCL", "ADBE", "CRM", "AMD", "ACN", "CSCO"],
    "Gesundheitswesen": ["LLY", "UNH", "JNJ", "MRK", "ABBV", "TMO", "DHR", "ABT", "PFE", "AMGN"],
    "Finanzwesen": ["BRK-B", "JPM", "V", "MA", "BAC", "WFC", "SPGI", "GS", "MS", "AXP"],
    "Nicht-Basiskonsumgüter": ["AMZN", "TSLA", "HD", "MCD", "NKE", "LOW", "SBUX", "BKNG", "TJX", "TGT"],
    "Kommunikationsdienste": ["GOOGL", "META", "NFLX", "DIS", "CMCSA", "TMUS", "VZ", "T", "CHTR", "EA"],
    "Industrie": ["GE", "CAT", "HON", "BA", "UNP", "UPS", "RTX", "LMT", "DE", "ADP"],
    "Basiskonsumgüter": ["PG", "PEP", "KO", "WMT", "COST", "PM", "MO", "MDLZ", "TGT", "CL"],
    "Energie": ["XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "OXY", "WMB"],
    "Versorger": ["NEE", "DUK", "SO", "SRE", "AEP", "D", "EXC", "XEL", "ED", "PEG"],
    "Immobilien": ["PLD", "AMT", "EQIX", "WELL", "PSA", "SPG", "O", "DLR", "CSGP", "CCI"],
    "Rohstoffe": ["LIN", "SHW", "FCX", "ECL", "NEM", "APD", "NUE", "DOW", "CTVA", "VMC"]
}